config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  resources :recipes do
    get 'search', on: :collection
  end

  get 'playground' => 'static_pages#playground'
  get 'about'      => 'static_pages#about'
  get 'todo'       => 'static_pages#todo'
  root 'static_pages#home'
end

app/models/contain.rb
class Contain < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :contains, dependent: :destroy
  has_many :recipes,  through:   :contains

  validates :name,         length: { minimum:  2 }

  default_scope { order('name') }
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :contains, dependent: :destroy
  has_many :ingredients, through: :contains

  validates :name,         length: { minimum:  2 }
  validates :instructions, length: { minimum: 20 }
  validates :difficulty,   inclusion: { in: 1..5 }
  validates :grade,        inclusion: { in: 1..5 }

  def self.fuzzy_find_by_name( s )
    includes(:ingredients).where(arel_table[:name].matches("%#{s}%"))
  end

  def self.find_by_ingredients( wanted_ingredients )
    # ids have to be integers, have to be uniq, cannot be 0
    ingredient_ids = wanted_ingredients.map(&:to_i).uniq.keep_if{|id| id > 0 }

    no_of_ingredients = ingredient_ids.length

    # turn into a string, separated by commas
    ingredient_ids_csv = ingredient_ids.join(",")

    # find recipe who contain ALL the specified ingredients
    recipe_ids = Contain.includes(:ingredients).find_by_sql(<<-END_SQL).map{|r| r.recipe_id}
      SELECT recipe_id, count(recipe_id) 
      FROM contains  
      WHERE ingredient_id IN ( #{ingredient_ids_csv} ) 
      GROUP BY recipe_id 
      HAVING count(recipe_id) = #{no_of_ingredients}
    END_SQL

    Recipe.find( recipe_ids )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { render inline: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to ingredients_path, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    if ! params[:search].blank? then
      @recipes = Recipe.fuzzy_find_by_name( params[:search] )
      @description = "Rezepte mit '#{params[:search]}' im Namen"
    elsif ! params[:wanted_ingredient_ids].nil? and ! params[:wanted_ingredient_ids].empty? then
      @recipes = Recipe.find_by_ingredients( params[:wanted_ingredient_ids] )
      ingredients = Ingredient.find( params[:wanted_ingredient_ids] ).map(&:name)
      @description = "Rezepte die #{ingredients.join(' und ')} enthalten"
    else
      @recipes = Recipe.includes(:ingredients).all
      @description = "Alle Rezepte"
    end
  end

  # GET /recipes/search
  def search
    @ingredients = Ingredient.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def recipe_params
    params.require(:recipe).permit(:name, :difficulty, :grade, :quantity, :minutes, :instructions, :ingredient_ids => [])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def home
  end

  def playground
  end

  def todo
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # translate flash types (success, error, alert, notice) 
  # to bootstrap class names
  def bootstrap_class_for flash_type
    { "success" => "alert-success", 
      "error"   => "alert-danger", 
      "alert"   => "alert-warning", 
      "notice"  => "alert-info"      }[flash_type] || "nope"
  end

end

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/ingredients/edit.html.erb
<% content_for :heading do %>
  <h1>Zutat umbenennen</h1>
<% end %>
<%= render 'form' %>

app/views/ingredients/edit.js.erb
$("#ingredient_<%= @ingredient.id %>").html('<%= escape_javascript render 'form' %>');

app/views/ingredients/index.html.erb
<% content_for :heading do %>
  <h1>Zutaten</h1>
<% end %>

<p><%= link_to 'Neue Zutat', new_ingredient_path %></p>

<% @ingredients.each do |ingredient| %>
  <p id="ingredient_<%= ingredient.id %>"><span><%= ingredient.name %></span>
  <%= link_to 'Edit', edit_ingredient_path(ingredient), remote:true , class: 'edit_ingredient' %>
  <%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/ingredients/new.html.erb
<% content_for :heading do %>
  <h1>Neue Zutat</h1>
<% end %>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cookin' on Rails  - <%= controller_name %> <%= action_name %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
  <div class="container-fullwidth" id="headerbar">
    <div class="container">
      <h2>
        <%= link_to root_path do %>
          <%= image_tag "logo.svg" %> Cookin' on Rails
        <% end %>
      </h2>
     </div>
  </div>

  <div id="main-container" class="container">
    <div class="row">
      <div class="col-xs-3"></div>
      <div class="col-xs-9">
        <% flash.each do |name, msg| -%>
          <%= content_tag :div, msg, class: "flash alert fade in " + bootstrap_class_for(name) %>
        <% end -%>
      </div>
    </div>

    <div class="row subheading">
      <div class="col-xs-3">
        &nbsp;
      </div>
      <div class="col-xs-9">
        <%= yield :heading %>
      </div>
    </div>

    <div class="row">
      <div id="sidebar" class="col-xs-3">
        <ul class="nav nav-pills nav-stacked">
          <li><%= link_to_unless_current "Home", root_path %></li>
          <li><%= link_to_unless_current "All Recipes", recipes_path , data: { confirm: 'Are you sure?' } %></li>
          <li><%= link_to_unless_current "Search Recipe", search_recipes_path %></li>
          <li><%= link_to_unless_current "Add New Repice", new_recipe_path %></li>
          <li><%= link_to_unless_current "JS Playground", playground_path %></li>
          <li><%= link_to_unless_current "About", about_path %></li>
          <li><%= link_to_unless_current "ToDo", todo_path %></li>

        </ul>
      </div>
      <div id="content" class="col-xs-9">
        <%= yield %>
      </div>
    </div>
  </div>

  <div class="container-fullwidth" id="footerbar">
    <div class="container">
      Icon made by <a href="http://www.flaticon.com/free-icon/kitchen-cooking-utensils_26253">Freepik</a> from <a href="http://www.flaticon.com">www.flaticon.com</a> |
      <a href="https://upload.wikimedia.org/wikipedia/commons/2/25/Koelkast_open.jpg">picture of fridge</a> by    M.Minderhoud under CC-BY-SA. |
      Recipes from <a href="https://www.kochwiki.org/">kochwiki</a> under CC-BY-SA.
     </div>
  </div>  

</body>
</html>

app/views/recipes/_form.html.erb
<%= bootstrap_form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :name %>
  <%= f.text_area :instructions %>
  <%= f.number_field :difficulty %>
  <%= f.number_field :grade %>
  <%= f.number_field :quantity %>
  <%= f.number_field :minutes %>

  <% Ingredient.all.each do |ingredient| %>
    <div class="checkbox">
      <label>
        <%= check_box_tag "recipe[ingredient_ids][]", ingredient.id, @recipe.ingredient_ids.include?(ingredient.id) %>
        <%= ingredient.name %>
      </label>
    </div>
  <% end %>

  <p><%= link_to "Neue Zutat hinzufügen", new_ingredient_path, id: "new_ingredient_link" %></p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/_ingredients.html.erb
<ul>
  <% r.contains.each do |c| %>
    <li><%= c.ingredient.name %></li>
  <% end %>
</ul>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<% content_for :heading do %>
  <h1>Rezepte</h1>
  <p><%= @description %>.</p>
<% end %>


<% @recipes.each do |recipe| %>
<h2><%= link_to recipe.name, recipe %></h2>
  <div class="row">
    <div class="col-xs-3">
        <p> Schwierigkeit: <%= recipe.difficulty %> </p>
        <p> Bewertung: <%= recipe.grade %> </p>
        <p> Für <%= recipe.quantity %> Personen </p>
        <p> Zubereitungszeit: <%= recipe.minutes %> Minuten </p>
    </div>
    <div class="col-xs-6">
      <%= render :partial => "ingredients", :locals => { :r => recipe } %>
    </div>
  </div>
<% end %>

app/views/recipes/new.html.erb
<% content_for :heading do %>
  <h1>Neues Rezept speichern</h1>
<% end %>

<%= render 'form' %>

app/views/recipes/search.html.erb
<style>
  .multi {
     column-count:3;
  }
</style>

<% content_for :heading do %>
  <h1>Suche</h1>
<% end %>


<h2>Nach dem Namen des Rezeptes</h2>

<%= bootstrap_form_tag url: recipes_path, method: :get do |f| %>
  <%= f.text_field :search, label: 'Suchbegriff' %>
  <%= f.submit "Suchen" %>
<% end %>

<h2>Nach den gewünschten Zutaten</h2>


<%= bootstrap_form_tag url: recipes_path, method: :get do |f| %>
  <%= f.form_group :wanted_ingredient_ids do %>
    <% @ingredients.each do |ingredient| %>
      <label>
        <%= check_box_tag "wanted_ingredient_ids[]", ingredient.id %>
        <%= ingredient.name %>
      </label>
      <br>
    <% end %>
  <% end %>

  <div class="actions">
    <%= submit_tag "Suchen" %>
  </div>
<% end %>

app/views/recipes/show.html.erb
<% content_for :heading do %>
  <h1><%= @recipe.name %></h1>
<% end %>
<div class="row">
  <div class="col-xs-3">
    <p> Schwierigkeit: <%= @recipe.difficulty %> </p>
    <p> Bewertung: <%= @recipe.grade %> </p>
    <p> Für <%= @recipe.quantity %> Personen </p>
    <p> Zubereitungszeit: <%= @recipe.minutes %> Minuten </p>
  </div>
  <div class="col-xs-6">
    <%= render :partial => "ingredients", :locals => { :r => @recipe } %>
  </div>
</div>

<h2>Zubereitung</h2>

<%= @recipe.instructions %>

app/views/static_pages/about.html.erb
<% content_for :heading do %>
  <h1>About</h1>
<% end %>

<p>This is an example site for learning
about ruby on rails.</p>
<p>It's also a hommage to <a href="https://portfolio.multimediatechnology.at/projects/2012-social-cookin">an old project 
  by Christian Lehner</a>.</p>

app/views/static_pages/home.html.erb
<% content_for :heading do %>
  <h1>Welcome to Cookin' on Rails</h1>
<% end %>

<p>
  Who doesn't know this problem: the fridge is full, but you
  have no idea what to cook from all these ingredients?
</p>
<p><%= image_tag 'ingredients.jpg', alt: 'the fridge' %></p>
<p>
  This is where Cookin' on Rails can help you:<br>
</p>
<p>
  You can check all the ingredients you have at home
  and Cookin' on Rails searches the database for recipes you
  can cook from them.
  Or you can share you own recipes on this platform.
</p>

app/views/static_pages/playground.html.erb
<% content_for :heading do %>
  <h1>The Javascript Playground</h1>
<% end %>


<p>This is an implementation of the code-exapmle for
  <a href="https://backend-development.github.io/javascript_and_ajax.html#unobtrusive-javascript">unobstrusive javascript</a> in the chapter on 
  <a href="https://backend-development.github.io/javascript_and_ajax.html#unobtrusive-javascript">JavaScript and AJAX in Rails</a>.</p>


<p>
<a href="#" data-background-color="#990000">Paint it red</a>
<a href="#" data-background-color="#009900" data-text-color="#FFFFFF">Paint it green</a>
<a href="#" data-background-color="#000099" data-text-color="#FFFFFF">Paint it blue</a>
</p>


<p>This is the button for <a href="/todo">todo no 4</a></p> 


<p><button data-hello="world">Hello World</button></p>

app/views/static_pages/todo.html.erb
<% content_for :heading do %>
  <h1>ToDo</h1>
<% end %>


<ol>
  <li>
    <h2>Load seed data</h2>
    <p>What is seed data?  Where is the actual file located? 
    And what was that rake task to load it?</p>
    <p>A:Seed-Data allows us to create default data easily. (db/seeds.rb, db:seed)</p>
  </li>

  <li>
    <h2>Understand Unobstrusive JavaScript</h2>
    <p>Look at the HTML-Code for <a href="/ingredients">deleting and
      ingredient</a>: where does the JavaScript to confirm come from?</p>
    <p>Try applying the same to a normal navigation link - does it also show
    the confirmation-popup?</p>
    <p>Compare the code in the <%= link_to 'JavaScript Playground', playground_path %>
    with what you learned about unobstrusive JavaScript 
    <a href="https://backend-development.github.io/javascript_and_ajax.html#unobtrusive-javascript">in backend-development.github.io</a>. You will be needing it soon!</p>
    <p> A: Data Attribute</p>
    <p> A: data: { confirm: 'Are you sure?' }</p>
    <p> A: That's fine. Seperate HTML from JS</p>
  </li>

  <li>
    <h2>Use Plain JavaScript</h2>
    <p>Write JavaScript code that adds the current time
      to every page.</p>
    <p>There's nothing Rails specific about this, just a few
      lines of jQuery, a new Date and setInterval should suffice. </p>

    <p>A: asssets/javascript/application.js</p>
    <p>"$('#content').prepend('	&#60;p id="time"	&#62;	&#60;/p	&#62;')</p>

    <p>setInterval(
    () => {$('#time').html(new Date().toTimeString())}
    ,1000);"</p>
  </li>            

  <li>
    <h2>Use Ecmascript 6</h2>
    <p>Add the <a href="https://github.com/TannerRogalsky/sprockets-es6">gem sprockets-es6</a> to the rails app (as described 
      on the gems homepage)</p>
    <p>Now save the follwing ES6 class as <kbd>/app/assets/JavaScript/hello_world.js.es6:</p>
      <pre>class HelloWorld {  
    constructor(name) {
      this.name = name;
    }

    sayHello() {
      alert("Hello " + this.name);
    }
  }</pre>
    <p>Check if it is transpiled to JavaScript correctly!</p>
    <p>Now add code in <kbd>/app/assets/JavaScript/main.js.es6</kbd> to 
    use this class for the Greetings-Form on the homepage.
    Be unobstrusive about it!</p>

    <p>A: gem install sprockets-es6</p>
    <p>A: gem 'sprockets'</p>
    <p>A: gem 'sprockets-es6'</p>
    <p>A: add .es6 extension to file name</p>

    <p>let hello = new HelloWorld("Thomas & Patrick");</p>

    <p>hello.sayHello();</p>
  </li>

  <li>
    <h2>Use AJAX with Rails</h2>
    <p>In page <%= link_to 'ingredients', ingredients_path %>: 
    the 'edit' link should not link to another page, but
    load the edit-form right into the current page, replacing the
    display of the ingredient name</p>
    <p>Follow the <%= link_to 'explanation on backend-development.github.io', "https://backend-development.github.io/javascript_and_ajax.html#the-recipe-ingredients-example" %>.</p>

    <p>A: edit.js.erb # js code</p>
    <p>A: index.html.erb #add remote:true</p>
  </li>

  <li>
    <h2>Switch on Turbolinks</h2>
    <p>Uncomment turbolink in the Gemfile, bundle + restart the server</p>
    <p>Add the following to application.js:</p>
    <pre>//= require turbolinks</pre>
    <p>Can you detect a difference?  Check if your javascript is still run on page
      load, change your code if necessary!</p>
    <p>Turbolinks are on by default, you have been using them in your other rails apps 
      without noticing. </p>

    <p>A: https://github.com/turbolinks/turbolinks</p>
    <p>A: SPA perfomance</p>
    <p>JS will not be executed when navigating around</p>
    <p>$(window).bind("turbolinks:load", function() {
      // ...
      })</p>
  </li>  
</ol>